### ISSUE TITLE
Definir Músicas e efeitos sonoros 

### ISSUE THREAD

**Issue by MatielloAL** [desenvolvimento-software-22/heavensBird#18]
Eu, como, desenvolvedor desejo definir quais serão os efeitos sonoros e músicas utilizadas na primeira fase do jogo.

## Critérios de Aceitação

- [x] Definir efeitos sonoros das mecânicas da personagem principal
- [x] Definir musica tema da fase 1
- [x] Definir efeito sonoro de inimigos 
- [x] Criação de card para criar efeitos sonoros e/ou música
- [x] Criação de card para incluir sonoplastia na primeira fase.

**Comment by marcosat147** [comment]
* Som de espada
* Som de corrida
* Som de dano no inimigo
* Som do inimigo
* Som do cavaleiro
