### ISSUE TITLE
Definir a mecânica 

### ISSUE THREAD

**Issue by MatielloAL** [desenvolvimento-software-22/heavensBird#19]
Eu, como, desenvolvedor desejo definir quais mecânicas serão usadas na primeira fase do jogo

## Critérios de aceitação

- [x] Definir as mecânicas
- [x] Criação das card com estória de usuário de cada mecânica

**Comment by Mateus-S-B** [comment]
Mecânicas definidas: 
* Andar
* Pular
* Atacar
* Agarrar
* Power Up Roxo (Magia a distância)
* Desviar
* Interação cenário

**Comment by Mateus-S-B** [comment]
Eu, como jogador, desejo ter um dash (esquiva) para desviar mais facilmente de projéteis inimigos.

**Comment by Mateus-S-B** [comment]
Eu, como jogador, desejo ter uma magia que me permita lançar projéteis a longa distância.

**Comment by Mateus-S-B** [comment]
**Interação com o cenário**

Eu, como jogador, desejo poder interagir com o cenário para encontrar itens escondidos.

**Comment by Mateus-S-B** [comment]
### Agarrar

Eu, como jogador, desejo poder me agarrar em paredes.
