### ISSUE TITLE
Fazer tutorial do minigame

### ISSUE THREAD

**Issue by mardntas** [desenvolvimento-software-22/heavensBird#2]
Eu, como desenvolvedor, desejo fazer tutorial do minigama para ganhar contexto da ferramenta unity

**Comment by MatielloAL** [comment]
Eu e a Leticia fizemos.

**Comment by csreis72** [comment]
Eu, Diego e Mateus fizemos.

**Comment by Filipe-002** [comment]
eu e o Marcos fizemos.
