### ISSUE TITLE
Definir as artes da primeira fase

### ISSUE THREAD

**Issue by MatielloAL** [desenvolvimento-software-22/heavensBird#20]
Eu , como , desenvolvedor desejo definir quais artes e animações serão necessárias para a primeira fase do jogo.

## Critérios de Aceitação
- [x] Definir artes do cenário( cabana, pedra , cavaleiro , Sunrise,): Matiello
- [x] Definir HUD : Leticia 
- [x] Definir animação e arte do background 
- [x] Definir animação dos inimigos (andando, morrendo, ataque de projétil, pulo do slime grande):Leticia
- [x] Definir animação do personagem principal (andando, atacando, pulando, morrendo, idle, agarrar nas paredes): Marcelo
- [x] Definir artes das plataformas: Marcelo
- [x] Definir caixas de diálogo (niru e cavaleiro): Leticia
- [x] Criação das card das animações e artes necessárias.

**Comment by leticia-oliveira** [comment]
Artes definidas e divididas em grupos:
HUD;
Animação e arte do background (acredito que já esteja totalmente pronta);
Animação dos inimigos (andando, morrendo, ataque de projétil, pulo do slime grande);
Animação do personagem principal (andando, atacando, pulando, morrendo, idle, agarrar nas paredes);
Artes das plataformas;
Animação das caixas de diálogo (niru e cavaleiro);
Outros elementos da fase 1 (Cabana, pedra, cavaleiro, Sunrise);
