### ISSUE TITLE
Criar animações de movimentação

### ISSUE THREAD

**Issue by mardntas** [desenvolvimento-software-22/heavensBird#25]
Eu, como, jogador desejo ver a animação da personagem se movimentando para saber qual lado estou me movimentando.

## Critérios de Aceitação

- [x]  Criar animação da personagem caminhando para esquerda e direita
- [x]  Criar animação da personagem em espera (parada)
- [x] Criar animação da personagem pulando
- [x] Criar animação da personagem deslizando (dash)

**Comment by leticia-oliveira** [comment]
Sprites da Niru
https://drive.google.com/drive/folders/1g38nuS3-UB4ef2ceX4nqPXOqLraF2elK?usp=share_link
https://drive.google.com/drive/folders/14Fj7b_yceyyLoCELI6sRHGkbezM5Uq_g?usp=share_link
