### ISSUE TITLE
Criar esqueleto da fase 1

### ISSUE THREAD

**Issue by mardntas** [desenvolvimento-software-22/heavensBird#26]
Eu, como, jogador desejo ver o esqueleto da fase para saber onde caminhar e com o que posso interagir.

## Critérios de Aceitação

- [x]  Criar plataformas da fase 1 
- [x] Criar colisão com os blocos e plataformas
- [x] Delimitar visão do jogador (câmera)

**Comment by Mateus-S-B** [comment]
Link do esqueleto da fase 1: 
https://drive.google.com/file/d/1OOXumu6UKiavo5fcD5MyJDkojCgyF7-2/view?usp=share_link
