### ISSUE TITLE
Criar arte da HUD

### ISSUE THREAD

**Issue by leticia-oliveira** [desenvolvimento-software-22/heavensBird#28]
Eu, como desenvolvedor, desejo criar as artes necessárias para representar as pontuações referentes a vida, dinheiro e demais informações do jogador.
### Critérios de aceitação

- [x] Criar barra de vida (três corações)

- [x] Criar ícones que ficarão ao lado da contagem de moedas e itens

**Comment by MatielloAL** [comment]
https://drive.google.com/drive/folders/1zhilMQ5KJ3V5fFXXxbSz_J9EtkED6uqO
